// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BackupFile {
    /**
     * Creates a new BackupFile instance.
     * @param {Partial<BackupFile>} [$$source = {}] - The source object to create the BackupFile.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("base64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base64"] = "";
        }
        if (!("mime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupFile(/** @type {Partial<BackupFile>} */($$parsedSource));
    }
}

export class BackupStatus {
    /**
     * Creates a new BackupStatus instance.
     * @param {Partial<BackupStatus>} [$$source = {}] - The source object to create the BackupStatus.
     */
    constructor($$source = {}) {
        if (!("lastExportAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["lastExportAt"] = null;
        }
        if (!("overdue" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overdue"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupStatus(/** @type {Partial<BackupStatus>} */($$parsedSource));
    }
}

export class CsvFile {
    /**
     * Creates a new CsvFile instance.
     * @param {Partial<CsvFile>} [$$source = {}] - The source object to create the CsvFile.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CsvFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CsvFile(/** @type {Partial<CsvFile>} */($$parsedSource));
    }
}

export class Dashboard {
    /**
     * Creates a new Dashboard instance.
     * @param {Partial<Dashboard>} [$$source = {}] - The source object to create the Dashboard.
     */
    constructor($$source = {}) {
        if (!("range" in $$source)) {
            /**
             * @member
             * @type {DateRange}
             */
            this["range"] = (new DateRange());
        }
        if (!("totalTenths" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalTenths"] = 0;
        }
        if (!("byStudent" in $$source)) {
            /**
             * @member
             * @type {StudentEarnings[]}
             */
            this["byStudent"] = [];
        }
        if (!("dailySeries" in $$source)) {
            /**
             * @member
             * @type {DayTotal[]}
             */
            this["dailySeries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dashboard instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Dashboard}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField0_0($$parsedSource["range"]);
        }
        if ("byStudent" in $$parsedSource) {
            $$parsedSource["byStudent"] = $$createField2_0($$parsedSource["byStudent"]);
        }
        if ("dailySeries" in $$parsedSource) {
            $$parsedSource["dailySeries"] = $$createField3_0($$parsedSource["dailySeries"]);
        }
        return new Dashboard(/** @type {Partial<Dashboard>} */($$parsedSource));
    }
}

export class DateRange {
    /**
     * Creates a new DateRange instance.
     * @param {Partial<DateRange>} [$$source = {}] - The source object to create the DateRange.
     */
    constructor($$source = {}) {
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DateRange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DateRange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DateRange(/** @type {Partial<DateRange>} */($$parsedSource));
    }
}

export class DayTotal {
    /**
     * Creates a new DayTotal instance.
     * @param {Partial<DayTotal>} [$$source = {}] - The source object to create the DayTotal.
     */
    constructor($$source = {}) {
        if (!("localDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDate"] = "";
        }
        if (!("earnedKobo" in $$source)) {
            /**
             * tenths
             * @member
             * @type {number}
             */
            this["earnedKobo"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DayTotal instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DayTotal}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DayTotal(/** @type {Partial<DayTotal>} */($$parsedSource));
    }
}

export class LifetimeStats {
    /**
     * Creates a new LifetimeStats instance.
     * @param {Partial<LifetimeStats>} [$$source = {}] - The source object to create the LifetimeStats.
     */
    constructor($$source = {}) {
        if (!("earnedKobo" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["earnedKobo"] = 0;
        }
        if (!("seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seconds"] = 0;
        }
        if (!("sessionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LifetimeStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LifetimeStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LifetimeStats(/** @type {Partial<LifetimeStats>} */($$parsedSource));
    }
}

export class ManualGroupInput {
    /**
     * Creates a new ManualGroupInput instance.
     * @param {Partial<ManualGroupInput>} [$$source = {}] - The source object to create the ManualGroupInput.
     */
    constructor($$source = {}) {
        if (!("studentIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["studentIds"] = [];
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("localDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDate"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * honoured when HasStartedAt
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }
        if (!("hasStartedAt" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasStartedAt"] = false;
        }
        if (!("rateKobo" in $$source)) {
            /**
             * honoured when HasRate && len(StudentIDs)==1
             * @member
             * @type {number}
             */
            this["rateKobo"] = 0;
        }
        if (!("hasRate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasRate"] = false;
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManualGroupInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManualGroupInput}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("studentIds" in $$parsedSource) {
            $$parsedSource["studentIds"] = $$createField0_0($$parsedSource["studentIds"]);
        }
        return new ManualGroupInput(/** @type {Partial<ManualGroupInput>} */($$parsedSource));
    }
}

export class ReportData {
    /**
     * Creates a new ReportData instance.
     * @param {Partial<ReportData>} [$$source = {}] - The source object to create the ReportData.
     */
    constructor($$source = {}) {
        if (!("range" in $$source)) {
            /**
             * @member
             * @type {ReportRange}
             */
            this["range"] = (new ReportRange());
        }
        if (!("generatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generatedAt"] = "";
        }
        if (!("students" in $$source)) {
            /**
             * @member
             * @type {ReportStudent[]}
             */
            this["students"] = [];
        }
        if (!("grand" in $$source)) {
            /**
             * @member
             * @type {ReportTotals}
             */
            this["grand"] = (new ReportTotals());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField0_0($$parsedSource["range"]);
        }
        if ("students" in $$parsedSource) {
            $$parsedSource["students"] = $$createField2_0($$parsedSource["students"]);
        }
        if ("grand" in $$parsedSource) {
            $$parsedSource["grand"] = $$createField3_0($$parsedSource["grand"]);
        }
        return new ReportData(/** @type {Partial<ReportData>} */($$parsedSource));
    }
}

/**
 * Report types (mirror utils/report.ts on mobile).
 */
export class ReportRange {
    /**
     * Creates a new ReportRange instance.
     * @param {Partial<ReportRange>} [$$source = {}] - The source object to create the ReportRange.
     */
    constructor($$source = {}) {
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportRange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportRange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportRange(/** @type {Partial<ReportRange>} */($$parsedSource));
    }
}

export class ReportSessionRow {
    /**
     * Creates a new ReportSessionRow instance.
     * @param {Partial<ReportSessionRow>} [$$source = {}] - The source object to create the ReportSessionRow.
     */
    constructor($$source = {}) {
        if (!("localDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDate"] = "";
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("rateKobo" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rateKobo"] = 0;
        }
        if (!("earnedTenths" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["earnedTenths"] = 0;
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("hasNotes" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasNotes"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportSessionRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportSessionRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportSessionRow(/** @type {Partial<ReportSessionRow>} */($$parsedSource));
    }
}

export class ReportStudent {
    /**
     * Creates a new ReportStudent instance.
     * @param {Partial<ReportStudent>} [$$source = {}] - The source object to create the ReportStudent.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["archived"] = false;
        }
        if (!("currentRateKobo" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentRateKobo"] = 0;
        }
        if (!("sessionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionCount"] = 0;
        }
        if (!("totalSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSeconds"] = 0;
        }
        if (!("earnedTenths" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["earnedTenths"] = 0;
        }
        if (!("sessions" in $$source)) {
            /**
             * @member
             * @type {ReportSessionRow[]}
             */
            this["sessions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportStudent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportStudent}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField6_0($$parsedSource["sessions"]);
        }
        return new ReportStudent(/** @type {Partial<ReportStudent>} */($$parsedSource));
    }
}

export class ReportTotals {
    /**
     * Creates a new ReportTotals instance.
     * @param {Partial<ReportTotals>} [$$source = {}] - The source object to create the ReportTotals.
     */
    constructor($$source = {}) {
        if (!("sessionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionCount"] = 0;
        }
        if (!("totalSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSeconds"] = 0;
        }
        if (!("earnedTenths" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["earnedTenths"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportTotals instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportTotals}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportTotals(/** @type {Partial<ReportTotals>} */($$parsedSource));
    }
}

export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("studentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studentId"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * timer | manual
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * running | completed
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }
        if (!("endedAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["endedAt"] = null;
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["durationSeconds"] = null;
        }
        if (!("rateSnapshotKobo" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rateSnapshotKobo"] = 0;
        }
        if (!("earnedKobo" in $$source)) {
            /**
             * tenths of kobo; nil while running
             * @member
             * @type {number | null}
             */
            this["earnedKobo"] = null;
        }
        if (!("localDate" in $$source)) {
            /**
             * YYYY-MM-DD Africa/Lagos
             * @member
             * @type {string}
             */
            this["localDate"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["notes"] = null;
        }
        if (!("groupId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["groupId"] = null;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

export class SessionFilter {
    /**
     * Creates a new SessionFilter instance.
     * @param {Partial<SessionFilter>} [$$source = {}] - The source object to create the SessionFilter.
     */
    constructor($$source = {}) {
        if (!("studentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studentId"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }
        if (!("search" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["search"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionFilter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionFilter(/** @type {Partial<SessionFilter>} */($$parsedSource));
    }
}

export class SessionPatch {
    /**
     * Creates a new SessionPatch instance.
     * @param {Partial<SessionPatch>} [$$source = {}] - The source object to create the SessionPatch.
     */
    constructor($$source = {}) {
        if (!("studentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studentId"] = "";
        }
        if (!("hasStudentId" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasStudentId"] = false;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("hasSource" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasSource"] = false;
        }
        if (!("localDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localDate"] = "";
        }
        if (!("hasLocalDate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasLocalDate"] = false;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }
        if (!("hasStartedAt" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasStartedAt"] = false;
        }
        if (!("rateSnapshotKobo" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rateSnapshotKobo"] = 0;
        }
        if (!("hasRate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasRate"] = false;
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("hasDuration" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasDuration"] = false;
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("hasNotes" in $$source)) {
            /**
             * true => set ("" clears to NULL)
             * @member
             * @type {boolean}
             */
            this["hasNotes"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionPatch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionPatch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionPatch(/** @type {Partial<SessionPatch>} */($$parsedSource));
    }
}

export class StartupCheck {
    /**
     * Creates a new StartupCheck instance.
     * @param {Partial<StartupCheck>} [$$source = {}] - The source object to create the StartupCheck.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("integrityDetail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["integrityDetail"] = "";
        }
        if (!("runningCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["runningCount"] = 0;
        }
        if (!("runningSince" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["runningSince"] = 0;
        }
        if (!("isStale" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStale"] = false;
        }
        if (!("backupOverdue" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["backupOverdue"] = false;
        }
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("databasePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databasePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartupCheck instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartupCheck}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartupCheck(/** @type {Partial<StartupCheck>} */($$parsedSource));
    }
}

export class StopOptions {
    /**
     * Creates a new StopOptions instance.
     * @param {Partial<StopOptions>} [$$source = {}] - The source object to create the StopOptions.
     */
    constructor($$source = {}) {
        if (!("localDateOverride" in $$source)) {
            /**
             * "" = keep running row's date
             * @member
             * @type {string}
             */
            this["localDateOverride"] = "";
        }
        if (!("durationOverrideSeconds" in $$source)) {
            /**
             * honoured when HasDurationOverride
             * @member
             * @type {number}
             */
            this["durationOverrideSeconds"] = 0;
        }
        if (!("hasDurationOverride" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasDurationOverride"] = false;
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("hasNotes" in $$source)) {
            /**
             * when true, Notes (even "") replaces; "" clears
             * @member
             * @type {boolean}
             */
            this["hasNotes"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StopOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StopOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StopOptions(/** @type {Partial<StopOptions>} */($$parsedSource));
    }
}

export class Student {
    /**
     * Creates a new Student instance.
     * @param {Partial<Student>} [$$source = {}] - The source object to create the Student.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hourlyRateKobo" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hourlyRateKobo"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * active | archived
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Student instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Student}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Student(/** @type {Partial<Student>} */($$parsedSource));
    }
}

export class StudentEarnings {
    /**
     * Creates a new StudentEarnings instance.
     * @param {Partial<StudentEarnings>} [$$source = {}] - The source object to create the StudentEarnings.
     */
    constructor($$source = {}) {
        if (!("studentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["studentId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("earnedKobo" in $$source)) {
            /**
             * tenths
             * @member
             * @type {number}
             */
            this["earnedKobo"] = 0;
        }
        if (!("seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seconds"] = 0;
        }
        if (!("sessionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StudentEarnings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StudentEarnings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StudentEarnings(/** @type {Partial<StudentEarnings>} */($$parsedSource));
    }
}

export class SyncEngine {
    /**
     * Creates a new SyncEngine instance.
     * @param {Partial<SyncEngine>} [$$source = {}] - The source object to create the SyncEngine.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncEngine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncEngine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncEngine(/** @type {Partial<SyncEngine>} */($$parsedSource));
    }
}

export class SyncStatus {
    /**
     * Creates a new SyncStatus instance.
     * @param {Partial<SyncStatus>} [$$source = {}] - The source object to create the SyncStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * synced | syncing | offline | error
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("pendingCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pendingCount"] = 0;
        }
        if (!("lastSyncAt" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["lastSyncAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncStatus(/** @type {Partial<SyncStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DateRange.createFrom;
const $$createType1 = StudentEarnings.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = DayTotal.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = ReportRange.createFrom;
const $$createType7 = ReportStudent.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ReportTotals.createFrom;
const $$createType10 = ReportSessionRow.createFrom;
const $$createType11 = $Create.Array($$createType10);
