// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../database/sql/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ArchiveStudent(id) {
    return $Call.ByID(1903644894, id);
}

/**
 * @param {string[]} studentIDs
 * @param {string} $from
 * @param {string} to
 * @param {string} label
 * @returns {$CancellablePromise<$models.ReportData>}
 */
export function CollectReport(studentIDs, $from, to, label) {
    return $Call.ByID(2161249229, studentIDs, $from, to, label).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} name
 * @param {number} hourlyRateKobo
 * @returns {$CancellablePromise<$models.Student>}
 */
export function CreateStudent(name, hourlyRateKobo) {
    return $Call.ByID(922254854, name, hourlyRateKobo).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(id) {
    return $Call.ByID(1636697936, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteStudent(id) {
    return $Call.ByID(2006247087, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function DiscardRunningGroup() {
    return $Call.ByID(2636306381);
}

/**
 * ExportBackup bundles the local SQLite database (.db) + manifest into a compressed .zip.
 * @returns {$CancellablePromise<$models.BackupFile>}
 */
export function ExportBackup() {
    return $Call.ByID(1117934383).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.CsvFile>}
 */
export function ExportCSV() {
    return $Call.ByID(3359684303).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.BackupStatus>}
 */
export function GetBackupStatus() {
    return $Call.ByID(2742539813).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} kind
 * @returns {$CancellablePromise<$models.Dashboard>}
 */
export function GetDashboard(kind) {
    return $Call.ByID(578659863, kind).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} studentID
 * @returns {$CancellablePromise<$models.LifetimeStats>}
 */
export function GetLifetime(studentID) {
    return $Call.ByID(1473294378, studentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string[]} studentIDs
 * @param {string} $from
 * @param {string} to
 * @param {string} label
 * @returns {$CancellablePromise<string>}
 */
export function GetReportHTML(studentIDs, $from, to, label) {
    return $Call.ByID(1707628226, studentIDs, $from, to, label);
}

/**
 * @returns {$CancellablePromise<$models.Session[]>}
 */
export function GetRunningGroup() {
    return $Call.ByID(1161056539).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Session>}
 */
export function GetSession(id) {
    return $Call.ByID(1142900467, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.Student>}
 */
export function GetStudent(id) {
    return $Call.ByID(2434203172, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SyncStatus>}
 */
export function GetSyncStatus() {
    return $Call.ByID(4118062128).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {$models.SessionFilter} filter
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.Session[]>}
 */
export function ListSessions(filter, limit, offset) {
    return $Call.ByID(37536830, filter, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} studentID
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<$models.Session[]>}
 */
export function ListSessionsByStudent(studentID, limit, offset) {
    return $Call.ByID(1827569262, studentID, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {boolean} includeArchived
 * @returns {$CancellablePromise<$models.Student[]>}
 */
export function ListStudents(includeArchived) {
    return $Call.ByID(1000882447, includeArchived).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {$models.ManualGroupInput} input
 * @returns {$CancellablePromise<$models.Session[]>}
 */
export function LogManualGroup(input) {
    return $Call.ByID(2072358848, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MarkExported() {
    return $Call.ByID(1640999409);
}

/**
 * RestoreBackup restores a .zip backup (containing tracka.db or tracka.sql) + manifest.json.
 * @param {string} base64Data
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function RestoreBackup(base64Data, filename) {
    return $Call.ByID(3800467733, base64Data, filename);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function RestoreBackupDialog() {
    return $Call.ByID(1308384489);
}

/**
 * @param {sql$0.DB | null} cloudDB
 * @returns {$CancellablePromise<void>}
 */
export function SetCloudDB(cloudDB) {
    return $Call.ByID(2816952236, cloudDB);
}

/**
 * @param {string[]} studentIDs
 * @param {string} notes
 * @returns {$CancellablePromise<$models.Session[]>}
 */
export function StartTimer(studentIDs, notes) {
    return $Call.ByID(2615122298, studentIDs, notes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.StartupCheck>}
 */
export function StartupCheck() {
    return $Call.ByID(2551049552).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {number} endedAtMillis
 * @param {$models.StopOptions} opts
 * @returns {$CancellablePromise<$models.Session[]>}
 */
export function StopTimer(endedAtMillis, opts) {
    return $Call.ByID(3085516564, endedAtMillis, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SyncEngine | null>}
 */
export function SyncEngine() {
    return $Call.ByID(3560279058).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function SyncNow() {
    return $Call.ByID(1687776216);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function UnarchiveStudent(id) {
    return $Call.ByID(1268375325, id);
}

/**
 * @param {string} id
 * @param {$models.SessionPatch} patch
 * @returns {$CancellablePromise<$models.Session>}
 */
export function UpdateSession(id, patch) {
    return $Call.ByID(3641701066, id, patch).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} id
 * @param {string} name
 * @param {number} hourlyRateKobo
 * @returns {$CancellablePromise<$models.Student>}
 */
export function UpdateStudent(id, name, hourlyRateKobo) {
    return $Call.ByID(2539687149, id, name, hourlyRateKobo).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ReportData.createFrom;
const $$createType1 = $models.Student.createFrom;
const $$createType2 = $models.BackupFile.createFrom;
const $$createType3 = $models.CsvFile.createFrom;
const $$createType4 = $models.BackupStatus.createFrom;
const $$createType5 = $models.Dashboard.createFrom;
const $$createType6 = $models.LifetimeStats.createFrom;
const $$createType7 = $models.Session.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.SyncStatus.createFrom;
const $$createType10 = $Create.Array($$createType1);
const $$createType11 = $models.StartupCheck.createFrom;
const $$createType12 = $models.SyncEngine.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
