package main

import (
	"fmt"
	"strings"
)

// HTML earnings report — Go port of tracka-app/src/utils/report.ts.
// Printable light page (white paper, zinc ink).

func escapeHTML(s string) string {
	r := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
		"'", "&#39;",
	)
	return r.Replace(s)
}

func studentSection(s ReportStudent) string {
	var rows string
	if len(s.Sessions) == 0 {
		rows = `<tr><td class="empty" colspan="5">No sessions in this period</td></tr>`
	} else {
		var b strings.Builder
		for _, r := range s.Sessions {
			notes := ""
			if r.HasNotes {
				notes = escapeHTML(r.Notes)
			}
			fmt.Fprintf(&b, `<tr>
              <td>%s</td>
              <td>%s</td>
              <td>%s/hr</td>
              <td class="num">%s</td>
              <td class="notes">%s</td>
            </tr>`,
				formatLocalDate(r.LocalDate),
				formatDurationLong(r.DurationSeconds),
				formatNaira(float64(r.RateKobo)),
				previewEarnedKobo(r.EarnedTenths),
				notes,
			)
		}
		rows = b.String()
	}
	arch := ""
	if s.Archived {
		arch = ` <span class="tag">archived</span>`
	}
	plural := "s"
	if s.SessionCount == 1 {
		plural = ""
	}
	return fmt.Sprintf(`<section class="student">
    <div class="student-head">
      <h2>%s%s</h2>
      <div class="student-totals">
        %d session%s ·
        %s ·
        <strong>%s</strong>
      </div>
    </div>
    <table>
      <thead><tr><th>Date</th><th>Duration</th><th>Rate</th><th class="num">Earned</th><th>Notes</th></tr></thead>
      <tbody>%s</tbody>
    </table>
  </section>`, escapeHTML(s.Name), arch, s.SessionCount, plural,
		formatDurationLong(s.TotalSeconds), previewEarnedKobo(s.EarnedTenths), rows)
}

// BuildReportHTML renders the full printable document.
func BuildReportHTML(data ReportData) string {
	var b strings.Builder
	for _, s := range data.Students {
		b.WriteString(studentSection(s))
	}
	plural := "s"
	if len(data.Students) == 1 {
		plural = ""
	}
	return fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Tracka — Earnings report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
         color: #18181B; padding: 32px 36px; font-size: 12px; }
  .head { display: flex; justify-content: space-between; align-items: flex-end;
          border-bottom: 3px solid #18181B; padding-bottom: 12px; }
  .brand { font-size: 20px; font-weight: 700; letter-spacing: -0.5px; }
  .meta { text-align: right; color: #52525B; font-size: 11px; line-height: 1.5; }
  .grand { display: flex; gap: 12px; margin: 18px 0 6px; }
  .stat { flex: 1; border: 1px solid #E4E4E7; border-radius: 8px; padding: 12px 14px; }
  .stat .v { font-size: 18px; font-weight: 700; }
  .stat .l { color: #52525B; font-size: 10px; text-transform: uppercase; letter-spacing: 0.6px; margin-top: 2px; }
  .student { margin-top: 22px; page-break-inside: avoid; }
  .student-head { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 8px; }
  h2 { font-size: 14px; }
  .tag { font-size: 10px; color: #52525B; font-weight: 400; }
  .student-totals { color: #52525B; font-size: 11px; }
  .student-totals strong { color: #18181B; }
  table { width: 100%%; border-collapse: collapse; }
  th { text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px;
       color: #52525B; border-bottom: 1px solid #E4E4E7; padding: 6px 8px 6px 0; }
  td { border-bottom: 1px solid #F4F4F5; padding: 6px 8px 6px 0; vertical-align: top; }
  .num, td.num { text-align: right; padding-right: 0; font-variant-numeric: tabular-nums; }
  th.num { text-align: right; }
  .notes { color: #52525B; max-width: 180px; }
  .empty { color: #A1A1AA; padding: 10px 0; }
  .foot { margin-top: 28px; color: #A1A1AA; font-size: 10px; }
</style>
</head>
<body>
  <div class="head">
    <div class="brand">Tracka — Earnings report</div>
    <div class="meta">%s<br/>Generated %s</div>
  </div>
  <div class="grand">
    <div class="stat"><div class="v">%s</div><div class="l">Total earned</div></div>
    <div class="stat"><div class="v">%s</div><div class="l">Total time taught</div></div>
    <div class="stat"><div class="v">%d</div><div class="l">Sessions</div></div>
    <div class="stat"><div class="v">%d</div><div class="l">Student%s</div></div>
  </div>
  %s
  <div class="foot">Weeks start Monday · Times in Africa/Lagos · Generated by Tracka</div>
</body>
</html>`,
		escapeHTML(data.Range.Label), escapeHTML(data.GeneratedAt),
		previewEarnedKobo(data.Grand.EarnedTenths),
		formatDurationLong(data.Grand.TotalSeconds),
		data.Grand.SessionCount, len(data.Students), plural, b.String())
}
